# Generated by Django 6.0.3 on 2026-04-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Computers', 'Computers'), ('Mobile Phones', 'Mobile Phones'), ('Clothing', 'Clothing'), ('Home & Garden', 'Home & Garden'), ('Books', 'Books'), ('Toys & Games', 'Toys & Games'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Health & Beauty', 'Health & Beauty'), ('Automotive', 'Automotive'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
